# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('pass_date', models.DateField()),
                ('club_picture', models.FileField(upload_to='uploads/')),
                ('pass_source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_netid', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_club', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('is_staff', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='pass_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='passes.User'),
        ),
    ]
