# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NetId',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
