# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_auto_20180401_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='netid',
            new_name='NetId',
        ),
    ]
