# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_auto_20180406_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_create_pass', 'To create a pass'), ('can_distribute_pass', 'To distribute passes'))},
        ),
    ]
