# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_auto_20180407_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pass',
            name='transferrable',
            field=models.BooleanField(default=False),
        ),
    ]
