# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_auto_20180409_1921'),
        ('passes', '0003_auto_20180406_0018'),
    ]

    operations = [
    ]
