# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_auto_20180409_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='club_picture',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
