#!/usr/bin/python
import sys
import readline

count = 1
print('[')

max = len(open("latest").readlines())
f = open("latest", "r")

while count <= max:
    line = str.split(f.readline())
    print('\t\t{')
    print('\t\t\t\"model\": \"passes.Student\",')
    sys.stdout.write('\t\t\t\"pk\": ')
    sys.stdout.write(str(count))
    print(',')
    print('\t\t\t\t\"fields\": {')
    sys.stdout.write('\t\t\t\t\t \"username\": \"')
    sys.stdout.write(line[len(line)-2][1:-1])
    print('\",')
    sys.stdout.write('\t\t\t\t\t \"NetId\": \"')
    sys.stdout.write(line[len(line)-2][1:-1])
    print('\",')
    sys.stdout.write('\t\t\t\t\t \"name\": \"')
    for x in range(0, len(line)-3):
        sys.stdout.write(line[x])
        sys.stdout.write(' ')
    sys.stdout.write(line[len(line)-3])
    print('\",')
    sys.stdout.write('\t\t\t\t\t \"user_club\": \"')
    sys.stdout.write('None')
    print('\"')

    print('\t\t\t}')
    sys.stdout.write('\t\t}')
    if count < max:
        print(',')
    else:
        print('')
    count = count + 1

print(']')

f.close()
