# Generated by Django 2.0.3 on 2018-04-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_auto_20180405_0156'),
    ]

    operations = [
    ]
