# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_auto_20180407_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='officer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_club',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
