# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0007_merge_20180411_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='transferrable',
            new_name='transferable',
        ),
        migrations.AlterField(
            model_name='pass',
            name='club_picture',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
