# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0009_pass_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='color',
        ),
        migrations.AddField(
            model_name='pass',
            name='colors',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
