# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0010_auto_20180418_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='colors',
            new_name='color',
        ),
    ]
