# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0017_auto_20180510_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='club_picture',
        ),
    ]
